In [ ]:
library(data.table)
library(DT)

In [ ]:
#I have faced some problems to export data and find appropriate data. So, I create my own data table here.

In [ ]:
usstates <- data.frame(state.abb , state.area , state.center$x , state.center$y)
usstates2 <- data.frame(state.abb , state.division , state.name , state.region)
setDT(usstates)
setDT(usstates2)

In [ ]:
#To merge properly I jus wanted to change the name of the short name column.

In [ ]:
usstates2[, state.short := state.abb]
usstates2[, state.abb := NULL]
usstates2

In [ ]:
#I have filtered my rows as an i operation.

In [ ]:
usstates[ state.area %between% c(20000 , 50000) & state.center.x < -80 & !state.center.y %between% c(32.5,37.5) , ]

In [ ]:
#As mentioned in assignment sheet I have created new column by using another columns bu it has to be a meaningless one.

In [ ]:
usstates[, .(state.abb , state.nonsense = state.area / abs(state.center.x + state.center.y))]

In [ ]:
#I recorded my meaningless column as last column into my table.

In [ ]:
usstates[, state.nonsense := state.area / abs(state.center.x + state.center.y)]
usstates

In [ ]:
#I merged my usstates datatable and usstates 2 for making a meaningful dcast and melt operation.

In [ ]:
usstates_big <- merge(usstates[, .(state.abb ,state.area , state.center.x , state.center.y)] , usstates2 , by.x = "state.abb" ,by.y = "state.short")

In [ ]:
#I have created a usstates_big datatable as a merge of usstates and usstates2 datatables.

In [ ]:
usstates_area <- usstates_big[, .(sa_max = max(state.area) , sa_min = min(state.area) , sa_av = mean(state.area)), by = c("state.division","state.region")]
usstates_area

In [ ]:
#I made a dcast operation I used state.division and state.region columns as edges and my value variable has become average value of state areas.

In [ ]:
states_area_wide <- dcast(usstates_area, state.division ~ state.region , value.var = "sa_av")
states_area_wide

In [ ]:
#I melted them properly.

In [ ]:
melt(states_area_wide , id.vars = "state.division" ,  variable.name = "state.region2" , value.name = "sa_av2")